version: '3'
services:
    koha:
        build:
            context: .
            dockerfile: dists/${KOHA_IMAGE_OS}/Dockerfile
        cap_add:
            - ALL
        volumes:
            - ${SYNC_REPO}:/kohadevbox/koha
        tmpfs:
            - /cover_db
            - /tmp
        env_file:
            - ./env/defaults.env
        environment:
            COVERAGE: ${COVERAGE}
            RUN_TESTS_AND_EXIT: ${RUN_TESTS_AND_EXIT}
            LOCAL_USER_ID: ${LOCAL_USER_ID}
