version: '3'
services:
    koha:
        image: kohaaloha/koha-apt:${KOHA_IMAGE}
        cap_add:
            - ALL
        volumes:
            - ${SYNC_REPO}:/kohadevbox/koha
        tmpfs:
            - /cover_db
            - /tmp
        env_file:
            - .env
        environment:
            COVERAGE: ${COVERAGE}
            RUN_TESTS_AND_EXIT: ${RUN_TESTS_AND_EXIT}
            LOCAL_USER_ID: ${LOCAL_USER_ID}
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
