version: '3'
services:
    db:
        image: mysql:5.5
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: koha_kohadev
            MYSQL_USER: koha_kohadev
            MYSQL_PASSWORD: password
        networks:
            - kohanet
    es:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - kohanet
    koha:
        build: ./
        depends_on:
            - db
            - es
        cap_add:
            - SYS_NICE
            - DAC_READ_SEARCH
            - SETGID
            - SETUID
        volumes:
            - ${SYNC_REPO}:/kohadevbox/koha
        environment:
            KOHA_INSTANCE: kohadev
            KOHA_DB_PASSWORD: password
            DEBUG: ${DEBUG}
            LOCAL_USER_ID: ${LOCAL_USER_ID}
        networks:
            - kohanet
networks:
    kohanet:

